{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9df14af1-f91a-4c21-b218-d752b3c16854",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🔎 Filtered Interns (Data Science, stipend > 5000):\n",
      "   intern_id intern_name         track  stipend\n",
      "0          1       Aisha  Data Science     7000\n",
      "1          3       Sneha  Data Science     5500\n",
      "\n",
      "📊 Average Stipend Per Track:\n",
      "             track  avg_stipend\n",
      "0   Cyber Security       6000.0\n",
      "1     Data Science       5500.0\n",
      "2  Web Development       6250.0\n",
      "\n",
      "👥 Intern Count Per Track:\n",
      "             track  intern_count\n",
      "0   Cyber Security             1\n",
      "1     Data Science             3\n",
      "2  Web Development             2\n"
     ]
    }
   ],
   "source": [
    "import sqlite3\n",
    "import pandas as pd\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 1️⃣ Create Database Connection\n",
    "# --------------------------------------------------\n",
    "conn = sqlite3.connect(\":memory:\")\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 2️⃣ Create interns Table\n",
    "# --------------------------------------------------\n",
    "cursor.execute(\"\"\"\n",
    "CREATE TABLE interns (\n",
    "    intern_id INTEGER PRIMARY KEY,\n",
    "    intern_name TEXT,\n",
    "    track TEXT,\n",
    "    stipend INTEGER\n",
    ")\n",
    "\"\"\")\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 3️⃣ Insert Sample Data\n",
    "# --------------------------------------------------\n",
    "interns_data = [\n",
    "    (1, \"Aisha\", \"Data Science\", 7000),\n",
    "    (2, \"Rahul\", \"Web Development\", 4500),\n",
    "    (3, \"Sneha\", \"Data Science\", 5500),\n",
    "    (4, \"Arjun\", \"Cyber Security\", 6000),\n",
    "    (5, \"Neha\", \"Data Science\", 4000),\n",
    "    (6, \"Vikram\", \"Web Development\", 8000)\n",
    "]\n",
    "\n",
    "cursor.executemany(\"INSERT INTO interns VALUES (?, ?, ?, ?)\", interns_data)\n",
    "conn.commit()\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 4️⃣ FILTER:\n",
    "# Data Science interns with stipend > 5000\n",
    "# --------------------------------------------------\n",
    "filter_query = \"\"\"\n",
    "SELECT *\n",
    "FROM interns\n",
    "WHERE track = 'Data Science'\n",
    "AND stipend > 5000\n",
    "\"\"\"\n",
    "\n",
    "df_filtered = pd.read_sql_query(filter_query, conn)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 5️⃣ AGGREGATE:\n",
    "# Average stipend per track\n",
    "# --------------------------------------------------\n",
    "avg_query = \"\"\"\n",
    "SELECT track,\n",
    "       AVG(stipend) AS avg_stipend\n",
    "FROM interns\n",
    "GROUP BY track\n",
    "\"\"\"\n",
    "\n",
    "df_avg = pd.read_sql_query(avg_query, conn)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 6️⃣ COUNT:\n",
    "# Number of interns per track\n",
    "# --------------------------------------------------\n",
    "count_query = \"\"\"\n",
    "SELECT track,\n",
    "       COUNT(*) AS intern_count\n",
    "FROM interns\n",
    "GROUP BY track\n",
    "\"\"\"\n",
    "\n",
    "df_count = pd.read_sql_query(count_query, conn)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# 7️⃣ Display Results\n",
    "# --------------------------------------------------\n",
    "print(\"🔎 Filtered Interns (Data Science, stipend > 5000):\")\n",
    "print(df_filtered)\n",
    "\n",
    "print(\"\\n📊 Average Stipend Per Track:\")\n",
    "print(df_avg)\n",
    "\n",
    "print(\"\\n👥 Intern Count Per Track:\")\n",
    "print(df_count)\n",
    "\n",
    "# Close connection\n",
    "conn.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "57b4cd53-3780-498e-bc0a-72ce98f17a90",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
